"""Transaction exports: CSV and PDF statements.

``fpdf2`` is used rather than a headless-browser renderer because a statement is
a fixed-layout document, and adding Chromium to a demo project's dependency tree
to lay out a table is not a defensible trade.
"""
from __future__ import annotations

import csv
import io
from datetime import UTC, datetime
from decimal import Decimal
from typing import Iterable, Sequence

from fpdf import FPDF

from app.models.banking import Account, Transaction
from app.models.user import User

CSV_COLUMNS = [
    "reference",
    "occurred_at",
    "type",
    "channel",
    "status",
    "description",
    "merchant",
    "category",
    "counterparty",
    "debit",
    "credit",
    "fee",
    "balance_after",
    "currency",
    "fraud_score",
    "flagged",
]


def _fmt_dt(value: datetime | None) -> str:
    if value is None:
        return ""
    if value.tzinfo is None:
        value = value.replace(tzinfo=UTC)
    return value.strftime("%Y-%m-%d %H:%M:%S")


def _money(value: Decimal | None) -> str:
    return f"{value:.2f}" if value is not None else ""


def transactions_to_csv(rows: Sequence[Transaction]) -> bytes:
    """Serialise transactions to CSV with separate debit/credit columns.

    Split columns rather than one signed amount: that is the convention every
    spreadsheet and accounting import expects.
    """
    buffer = io.StringIO(newline="")
    writer = csv.writer(buffer, quoting=csv.QUOTE_MINIMAL, lineterminator="\r\n")
    writer.writerow(CSV_COLUMNS)

    for t in rows:
        debit = t.amount if t.signed_amount < 0 else None
        credit = t.amount if t.signed_amount > 0 else None
        writer.writerow(
            [
                t.reference,
                _fmt_dt(t.occurred_at),
                t.txn_type,
                t.channel,
                t.status,
                t.description or "",
                t.merchant_name or "",
                t.merchant_category,
                t.counterparty_name or "",
                _money(debit),
                _money(credit),
                _money(t.fee) if t.fee else "",
                _money(t.balance_after),
                t.currency,
                f"{t.fraud_score:.4f}" if t.fraud_score is not None else "",
                "yes" if t.is_flagged else "",
            ]
        )
    # BOM so Excel opens UTF-8 correctly instead of mangling non-ASCII names.
    return buffer.getvalue().encode("utf-8-sig")


class _StatementPDF(FPDF):
    """A4 portrait statement with a repeating header and page numbers."""

    def __init__(self, *, bank: str, title: str) -> None:
        super().__init__(orientation="P", unit="mm", format="A4")
        self.bank = bank
        self.title_text = title
        self.set_auto_page_break(auto=True, margin=18)
        self.set_margins(12, 12, 12)

    def header(self) -> None:
        self.set_font("Helvetica", "B", 15)
        self.set_text_color(17, 24, 39)
        self.cell(0, 8, self.bank, new_x="LMARGIN", new_y="NEXT")
        self.set_font("Helvetica", "", 10)
        self.set_text_color(90, 90, 90)
        self.cell(0, 5, self.title_text, new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(215, 215, 215)
        self.line(12, self.get_y() + 1.5, 198, self.get_y() + 1.5)
        self.ln(4)

    def footer(self) -> None:
        self.set_y(-14)
        self.set_font("Helvetica", "", 7.5)
        self.set_text_color(130, 130, 130)
        self.cell(
            0,
            4,
            "Simulated statement generated by IntelliBank, an educational project. "
            "Not a financial document.",
            new_x="LMARGIN",
            new_y="NEXT",
            align="C",
        )
        self.cell(0, 4, f"Page {self.page_no()}/{{nb}}", align="C")


def _ascii(text: str) -> str:
    """fpdf2's core fonts are Latin-1 only; drop anything they cannot encode."""
    return text.encode("latin-1", "replace").decode("latin-1")


def transactions_to_pdf(
    rows: Sequence[Transaction],
    *,
    user: User,
    account: Account | None = None,
    period_from: datetime | None = None,
    period_to: datetime | None = None,
    bank_name: str = "IntelliBank",
) -> bytes:
    """Render an account statement with a summary block and a transaction table."""
    period = "All transactions"
    if period_from or period_to:
        start = period_from.strftime("%d %b %Y") if period_from else "beginning"
        end = period_to.strftime("%d %b %Y") if period_to else "today"
        period = f"Statement period: {start} to {end}"

    pdf = _StatementPDF(bank=bank_name, title=_ascii(period))
    pdf.alias_nb_pages()
    pdf.add_page()

    # ---- account holder block ----
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(17, 24, 39)
    pdf.cell(0, 5.5, "Account holder", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 9.5)
    pdf.set_text_color(60, 60, 60)
    pdf.cell(0, 5, _ascii(user.full_name), new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 5, _ascii(user.email), new_x="LMARGIN", new_y="NEXT")
    if account is not None:
        pdf.cell(
            0,
            5,
            _ascii(
                f"Account {account.account_number}  |  {account.account_type.replace('_', ' ').title()}"
                f"  |  IFSC {account.ifsc_code}"
            ),
            new_x="LMARGIN",
            new_y="NEXT",
        )
        pdf.set_font("Helvetica", "B", 9.5)
        pdf.cell(
            0,
            5,
            _ascii(f"Closing balance: {account.currency} {account.balance:,.2f}"),
            new_x="LMARGIN",
            new_y="NEXT",
        )
    pdf.ln(3)

    # ---- summary ----
    debits = sum((t.amount for t in rows if t.signed_amount < 0), Decimal("0"))
    credits = sum((t.amount for t in rows if t.signed_amount > 0), Decimal("0"))
    flagged = sum(1 for t in rows if t.is_flagged)

    pdf.set_fill_color(246, 247, 249)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(40, 40, 40)
    summary = (
        f"Transactions: {len(rows)}    Money in: {credits:,.2f}    "
        f"Money out: {debits:,.2f}    Net: {credits - debits:,.2f}"
    )
    if flagged:
        summary += f"    Flagged for review: {flagged}"
    pdf.cell(0, 7, _ascii("  " + summary), border=0, fill=True, new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)

    # ---- table ----
    widths = [26, 30, 56, 22, 24, 28]
    headers = ["Date", "Reference", "Description", "Type", "Amount", "Balance"]

    def _table_header() -> None:
        pdf.set_font("Helvetica", "B", 8.5)
        pdf.set_fill_color(30, 41, 59)
        pdf.set_text_color(255, 255, 255)
        for w, h in zip(widths, headers):
            pdf.cell(w, 6.5, f" {h}", border=0, fill=True, align="R" if h in ("Amount", "Balance") else "L")
        pdf.ln(6.5)
        pdf.set_text_color(35, 35, 35)

    _table_header()
    pdf.set_font("Helvetica", "", 8)

    for i, t in enumerate(rows):
        # Reserve room for the footer; re-print the table head on the new page.
        if pdf.get_y() > 262:
            pdf.add_page()
            _table_header()
            pdf.set_font("Helvetica", "", 8)

        if i % 2 == 0:
            pdf.set_fill_color(250, 250, 251)
            fill = True
        else:
            fill = False

        desc = t.description or t.merchant_name or t.merchant_category
        signed = f"{'-' if t.signed_amount < 0 else '+'}{t.amount:,.2f}"

        pdf.cell(widths[0], 5.6, f" {t.occurred_at.strftime('%d %b %y')}", fill=fill)
        pdf.cell(widths[1], 5.6, f" {_ascii(t.reference)}", fill=fill)
        pdf.cell(widths[2], 5.6, f" {_ascii(desc)[:34]}", fill=fill)
        pdf.cell(widths[3], 5.6, f" {t.txn_type.replace('_', ' ')[:12]}", fill=fill)
        pdf.cell(widths[4], 5.6, f"{signed} ", align="R", fill=fill)
        pdf.cell(
            widths[5],
            5.6,
            f"{t.balance_after:,.2f} " if t.balance_after is not None else "- ",
            align="R",
            fill=fill,
        )
        pdf.ln(5.6)

    if not rows:
        pdf.set_font("Helvetica", "I", 9)
        pdf.set_text_color(120, 120, 120)
        pdf.cell(0, 8, "  No transactions in this period.", new_x="LMARGIN", new_y="NEXT")

    pdf.ln(4)
    pdf.set_font("Helvetica", "", 7.5)
    pdf.set_text_color(130, 130, 130)
    pdf.multi_cell(
        0,
        4,
        _ascii(
            f"Generated {datetime.now(UTC).strftime('%d %b %Y %H:%M UTC')}. "
            "IntelliBank is a simulated banking platform built for educational and "
            "portfolio purposes. It holds no real funds and is not a licensed "
            "financial institution."
        ),
    )
    return bytes(pdf.output())


def export_filename(prefix: str, extension: str, account_number: str | None = None) -> str:
    stamp = datetime.now(UTC).strftime("%Y%m%d")
    middle = f"_{account_number}" if account_number else ""
    return f"{prefix}{middle}_{stamp}.{extension}"
